

apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: octops-path
  labels:
    cluster: gke-1.24
    region: us-east-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        cluster: gke-1.24
        region: us-east-1
      annotations:
        octops-kubernetes.io/ingress.class: "contour" #required for Contour to handle ingress
        octops.io/gameserver-ingress-mode: "path"
#        octops.io/gameserver-ingress-fqdn: "servers.example.com,servers.example.gg"
        octops.io/gameserver-ingress-fqdn: "servers.example.com"
        octops-projectcontour.io/websocket-routes: "/{{ .Name }}" #required for Contour to enable websocket, use template to define values
        #octops.io/tls-secret-name: "custom-secret"
        #octops.io/terminate-tls: "true"
        #octops.io/issuer-tls-name: "selfsigned-issuer"
    spec:
      ports:
        - name: default
          containerPort: 8088
          protocol: TCP
      template:
        spec:
          containers:
            - name: gameserver
              image: gcr.io/agones-images/udp-server:0.21
              imagePullPolicy: Always
              #image: octops/gameserver-http:latest
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "20m"
                limits:
                  memory: "64Mi"
                  cpu: "20m"